# Learning numpy

# Array Creation: Conversion from lists & some attributes

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
arr = np.array([1,2,3,4,5], np.int8)

In [5]:
arr

array([1, 2, 3, 4, 5], dtype=int8)

In [6]:
arr = np.array([[1,2,3,4,5]])

In [7]:
arr[0,1]

2

In [8]:
arr.shape

(1, 5)

In [9]:
arr = np.array([[1,2,3,4,5]], np.int8)

In [10]:
arr.dtype

dtype('int8')

In [11]:
arr = np.array([[1,2,3,4,5]])

In [12]:
arr[0,4]=6

In [13]:
arr


array([[1, 2, 3, 4, 6]])

In [14]:
arr.nbytes 

20

In [15]:
list_arr=np.array([[1,2,3],[4,5,6,],[7,8,9]])

In [16]:
list_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
list_arr.ndim

2

# Arrays from Existing Data

**1.asarray()**

In [18]:
abc=np.array([[1,2,3],[4,5,6,],[7,8,9]])

In [19]:
xyz=np.asarray(abc,dtype="float",order="F") #Row Major=C & Column Major = "F",to print nditer() is used
xyz                               

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [20]:
for i in np.nditer(xyz):
    print (i)
    

1.0
4.0
7.0
2.0
5.0
8.0
3.0
6.0
9.0


**2.frombuffer()**

In [21]:
q=b"I am learning numpy" #b means data is stored in bytes

In [22]:
l=np.frombuffer(q,dtype="S1",count=-1,offset=0)
#count =-1 is default and takes all values and offset is the index of starting value &S1=1 byte data
l

array([b'I', b' ', b'a', b'm', b' ', b'l', b'e', b'a', b'r', b'n', b'i',
       b'n', b'g', b' ', b'n', b'u', b'm', b'p', b'y'], dtype='|S1')

**3.fromiter()**

In [23]:
lst=[10.0,20,30.0,40]

In [24]:
iterr=np.fromiter(lst,dtype="int",count=2)
iterr

array([10, 20])

# Arrays with Numerical Ranges

**1.arange()** 

In [25]:
np.arange(0,10,2,dtype="int")#This gives the arrauy of the list; #arange() doesnt give stop value

array([0, 2, 4, 6, 8])

In [26]:
ary=np.arange(0,10,2,dtype="int")


In [27]:
print(ary) #This process gives array(space seperated value)

[0 2 4 6 8]


**2.linspace()**

In [28]:
arrr=np.linspace(0,10,5)

In [29]:
print(arrr) #linspace includes stop value by default

[ 0.   2.5  5.   7.5 10. ]


In [30]:
arrr=np.linspace(0,10,5,endpoint=False) #endpoint is used to exclude stop value

In [31]:
print(arrr)

[0. 2. 4. 6. 8.]


In [32]:
arrr=np.linspace(0,10,5,endpoint=False,
                 retstep=True) #retstep is false by default

In [33]:
print(arrr)

(array([0., 2., 4., 6., 8.]), 2.0)


In [34]:
lss=np.linspace((1,2),(10,20),10)
lss

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

**3.logspace()**

In [35]:
larrr=np.logspace(0,10,5,endpoint=False,base=2)

In [36]:
print(larrr)

[  1.   4.  16.  64. 256.]


**4.random.randint()**

In [37]:
rarr1=np.random.rand(10)
rarr1

array([0.39119444, 0.502074  , 0.79477879, 0.36221772, 0.92377521,
       0.60940576, 0.48439787, 0.61068971, 0.31787178, 0.74671582])

In [38]:
rarr2=np.random.rand(3,3)
rarr2

array([[0.71200357, 0.13258724, 0.3311297 ],
       [0.71012327, 0.18262292, 0.630994  ],
       [0.39014848, 0.52740123, 0.51652418]])

In [39]:
rarr2.dtype

dtype('float64')

In [40]:
rarr3=np.random.randint(0,50,30) #Randint gives random integer
rarr3

array([41, 19, 47,  5, 33, 11,  9, 18,  1,  6, 39, 45, 22, 36, 39, 43, 12,
       22, 44, 29, 26, 20, 19, 22, 24, 47,  0, 48,  0, 46])

# shape() , reshape()

In [41]:
aa32=([[1,4],[6,9],[20,60]])


In [42]:
a32=np.array(aa32)
a32

array([[ 1,  4],
       [ 6,  9],
       [20, 60]])

In [43]:
np.shape(a32)

(3, 2)

In [44]:
np.reshape(a32,(2,3))

array([[ 1,  4,  6],
       [ 9, 20, 60]])

In [45]:
np.reshape(a32,-1) #Converted 3D into 1D array

array([ 1,  4,  6,  9, 20, 60])

# Initialization of arrays

**1.zeros()**



In [46]:
np.zeros((3,4))#default dtype = float in numpy

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.zeros((3,4),dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

**2.ones()**

In [48]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

**3.full()**

In [49]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

# Accessing elements of ndarray

**1.1D Array**


In [50]:
one=np.array([22,4,6])
one

array([22,  4,  6])

In [51]:
one[2]

6

**2.2D Array**


In [52]:
two=np.array([[22,4,6],[25,70,90]])
two

array([[22,  4,  6],
       [25, 70, 90]])

In [53]:
two[0,2]

6

**3.3D Array**

In [54]:
three=np.array([[[22,4,6],[

],[[65,45,69],[5,7,9]]])
three

array([[[22,  4,  6],
        [25, 70, 90]],

       [[65, 45, 69],
        [ 5,  7,  9]]])

In [55]:
three[0,1,1]

70

# Slicing operation

**1.1D Array**

In [56]:
s133=np.array([22,4,6,4,8,9,34,67])
s133

array([22,  4,  6,  4,  8,  9, 34, 67])

In [57]:
s133[1:8:2]

array([ 4,  4,  9, 67])

**2.2D Array**

In [58]:
s2=np.array([[22,4,6,4,68],[25,70,90,34,45]])

In [59]:
s2[0,1:6:2]

array([4, 4])

In [60]:
s2[0:4,2:5] #2:5 is considered for slicing of both dimension


array([[ 6,  4, 68],
       [90, 34, 45]])

**3.3D Array**

In [61]:
s3=np.array([[[22,4,6,56,67],[25,70,90,88,66]],[[65,45,69,47,79],[5,7,9,98,67]]])

In [62]:
s3[0,1,0:3]

array([25, 70, 90])

In [63]:
s3[0:4,0:2,0:4]

array([[[22,  4,  6, 56],
        [25, 70, 90, 88]],

       [[65, 45, 69, 47],
        [ 5,  7,  9, 98]]])

# Axis Attribute

In [64]:
axs=np.array([[22,4,6,4],[25,7,0,3]])

In [65]:
np.sort(axs,axis=0) #Columnwise sorting

array([[22,  4,  0,  3],
       [25,  7,  6,  4]])

In [66]:
np.sort(axs,axis=1) #Rowise sorting

array([[ 4,  4,  6, 22],
       [ 0,  3,  7, 25]])

# Joining Arrays

In [67]:
fi=np.arange(6).reshape(2,3)
fi

array([[0, 1, 2],
       [3, 4, 5]])

In [68]:
se=np.arange(7,13).reshape(2,3)
se

array([[ 7,  8,  9],
       [10, 11, 12]])

**1.Concatenation()**

In [69]:
np.concatenate((fi,se)) #concatenate gives single array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [70]:
np.concatenate((fi,se),axis=1)#default axis=0

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

**2.Stack()**

In [71]:
np.stack((fi,se)) #stack gives two different array

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
np.stack((fi,se),axis=1)

array([[[ 0,  1,  2],
        [ 7,  8,  9]],

       [[ 3,  4,  5],
        [10, 11, 12]]])

**3.vstack()**

In [73]:
np.vstack((fi,se))#same as concatenate

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

**4.hstack()**

In [74]:
np.hstack((fi,se))

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

**5.dstack**

In [75]:
np.dstack((fi,se))#depth

array([[[ 0,  7],
        [ 1,  8],
        [ 2,  9]],

       [[ 3, 10],
        [ 4, 11],
        [ 5, 12]]])

# Splitting

**1.array_split()**

In [76]:
s1=np.arange(1,13)
s1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
s11=np.array_split(s1,2)
s11

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [78]:
s11[1]

array([ 7,  8,  9, 10, 11, 12])

In [79]:
s12=np.array_split(s1,9)
s12

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7]),
 array([8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

**2.hsplit()**

In [80]:
hs=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [81]:
np.hsplit(hs,5)

[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

**3.vsplit()**

In [82]:
np.vsplit(hs,2)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]

# Adding, Removing & sorting

**1.Insert()**

In [83]:
ara=np.array([1,4,8]) #Adds the element in between
ara

array([1, 4, 8])

In [84]:
ara1=np.insert(ara,1,2)
ara1

array([1, 2, 4, 8])

**2.Append()**

In [85]:
ara2=np.append(ara,5) #Adds the element in last
ara2

array([1, 4, 8, 5])

**3.Delete()**

In [86]:
ara3=np.delete(ara2, 1)
ara3

array([1, 8, 5])

**4.Sorting()**

In [87]:
arr4=np.random.randint(0,20,10)
arr4

array([10, 18, 16,  5,  4,  5, 13, 17, 17, 12])

In [88]:
np.sort(arr4)

array([ 4,  5,  5, 10, 12, 13, 16, 17, 17, 18])

# Copy() & View()

**1.Copy()**

In [89]:
cc=np.array([1,2,3,4,5])     
#copy()=Changes are not reflected which are made in main array and vice versa..it is just a copy
cc

array([1, 2, 3, 4, 5])

In [90]:
cc1=cc.copy()
cc1

array([1, 2, 3, 4, 5])

**2.View()**

In [91]:
vieww=cc.view()
vieww

array([1, 2, 3, 4, 5])

In [92]:
cc[0]=0

In [93]:
vieww    #view()=Changes are reflected which are made in main array and vice versa

array([0, 2, 3, 4, 5])

In [94]:
vieww[0]=9
vieww

array([9, 2, 3, 4, 5])

In [95]:
cc

array([9, 2, 3, 4, 5])

In [96]:
cc1

array([1, 2, 3, 4, 5])

# Searching an element in a given array

**1.where()**

In [97]:
eve=np.arange(1,25)
eve


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [98]:
np.where(eve%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23], dtype=int64),)

**2.searchsorted()**

In [99]:
ss=np.array([3,6,7,9,11,14,18,19])

In [100]:
np.searchsorted(ss,[5]) #gives the position whre the array is to be inserted

array([1], dtype=int64)

In [101]:
np.searchsorted(ss,[5,2,12,17])

array([1, 0, 5, 6], dtype=int64)

# Sorting in array of different data types

In [102]:
dd=np.dtype([('name','S10'),('Perc',float)])

In [103]:
dd1=np.array([('mit',90.2),('tima',50.4),('lom',60.9)],dtype=dd)

In [104]:
np.sort(dd1,order='name')

array([(b'lom', 60.9), (b'mit', 90.2), (b'tima', 50.4)],
      dtype=[('name', 'S10'), ('Perc', '<f8')])

In [105]:
np.sort(dd1,order='Perc')

array([(b'tima', 50.4), (b'lom', 60.9), (b'mit', 90.2)],
      dtype=[('name', 'S10'), ('Perc', '<f8')])

# Arithmetic Operations

In [106]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [107]:
b1=np.array([[6,3,1],[9,3,4],[1,3,5]])

In [108]:
c1=np.array([[2,3,4]])

In [109]:
d1=np.array([2])

In [110]:
e1=np.array([2,3])

In [111]:
np.add(a1,b1)

array([[ 7,  5,  4],
       [13,  8, 10],
       [ 8, 11, 14]])

In [112]:
np.add(a1,c1)

array([[ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [113]:
np.add(a1,d1)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

np.add(a1,e1) 
#second array should have atleast one dimension and he no. of elements in that dim should be same

In [114]:
np.subtract(a1,b1)

array([[-5, -1,  2],
       [-5,  2,  2],
       [ 6,  5,  4]])

In [115]:
np.multiply(a1,b1)

array([[ 6,  6,  3],
       [36, 15, 24],
       [ 7, 24, 45]])

In [116]:
np.divide(a1,b1)

array([[0.16666667, 0.66666667, 3.        ],
       [0.44444444, 1.66666667, 1.5       ],
       [7.        , 2.66666667, 1.8       ]])

In [117]:
np.mod(a1,d1)

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [118]:
np.power(a1,d1)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [119]:
np.reciprocal(a1)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [120]:
f1=np.array([2+3j,3-8j,7+3j])

In [121]:
np.real(f1)

array([2., 3., 7.])

In [122]:
np.imag(f1)

array([ 3., -8.,  3.])

In [123]:
np.conjugate(f1)

array([2.-3.j, 3.+8.j, 7.-3.j])

# Statistical Functions

In [124]:
sf=np.array([[6,3,2],[9,3,4],[8,3,5]])

In [125]:
np.amin(sf)

2

In [126]:
np.amax(sf)

9

In [127]:
np.amin((sf),axis=0)

array([6, 3, 2])

In [128]:
np.average(sf)

4.777777777777778

In [129]:
np.average((sf),axis=1)

array([3.66666667, 5.33333333, 5.33333333])

In [130]:
w=[1,2,3]
w

[1, 2, 3]

In [131]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [132]:
np.average(a1,weights=w,axis=1) #weight average

array([2.33333333, 5.33333333, 8.33333333])

In [133]:
np.mean(a1)

5.0

In [134]:
m=np.array([1,2,3,4,5,6,7,8])

In [135]:
np.median(m)

4.5

In [136]:
np.var(sf) #variance

5.283950617283951

In [137]:
np.std(sf) #standard deviation

2.298684540619689

# Aggregation

**1.sum()**

In [138]:
summ=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [139]:
summ.sum()

45

In [140]:
summ.sum(axis=0)

array([12, 15, 18])

**2.prod()**

In [141]:
summ.prod()

362880

# Unique 

**1.unique()**

In [142]:
u=np.array([1,2,3,5,6,8,3,4,5,6,7,8,9])

In [143]:
np.unique(u)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
u1=np.array([[1,2,3,2,3],[4,5,6,5,5],[7,8,9,7,9]])

#  Array Creation: Intrinsic Numpy array creation objects

In [145]:
lspace=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [146]:
emp=np.empty([2,3])
emp

array([[0., 0., 0.],
       [0., 0., 0.]])

In [147]:
emp1=np.full([2,3],5)
emp1

array([[5, 5, 5],
       [5, 5, 5]])

In [148]:
emp_like=np.empty_like(lspace)  #takes size of lspace array and makes an empty array
emp_like                      

array([[          0,           0, -1257436224],
       [        206, -1257435136,         206],
       [-1257432960,         206,     7209065]])

In [149]:
emptyy=np.empty([4,3])
emptyy

array([[4.38631758e-312, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 2.37663529e-312, 5.74084271e+169],
       [4.22374550e-090, 5.98633990e+174, 5.41617681e-067],
       [1.54567798e+185, 3.99910963e+252, 4.93432906e+257]])

In [150]:
emptyy.fill(4)
emptyy

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [151]:
ide=np.identity(10) #Creates an identity matrix 10*10
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [152]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [153]:
arr = arr.reshape(3,33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [154]:
arr=arr.ravel() #creates 1D array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [155]:
arr.shape

(99,)

In [156]:
x=([1,2,3],[4,5,6],[7,8,9])

In [157]:
ar=np.array(x)

In [158]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [159]:
ar.T  #Transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [160]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
ar.flat #Gives iterator

In [162]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [163]:
ar.ndim

2

In [164]:
ar.size

9

In [165]:
ar.nbytes #How much bytes are consumed


36

In [166]:
one=np.array([1,45,788,4])

In [167]:
one

array([  1,  45, 788,   4])

In [168]:
one.argmax() #It is a function() which gives the index of highest value

2

In [169]:
one.argmin()

0

In [170]:
one.argsort() #It is a function() which gives index values in ascending order

array([0, 3, 1, 2], dtype=int64)

In [171]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [172]:
ar.argmin()

0

In [173]:
ar.argmax()

8

In [174]:
y=([31,24,53],[40,52,26],[97,78,89])

In [175]:
a=np.array(y)

In [176]:
a

array([[31, 24, 53],
       [40, 52, 26],
       [97, 78, 89]])

In [177]:
a.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [178]:
a.argmax(axis=1)

array([2, 1, 0], dtype=int64)

In [179]:
a.argsort(axis=1)

array([[1, 0, 2],
       [2, 0, 1],
       [1, 2, 0]], dtype=int64)

In [180]:
ar1=np.array([[3, 2, 5],
       [0, 5, 2],
       [9, 8, 9]])

In [181]:
ar1

array([[3, 2, 5],
       [0, 5, 2],
       [9, 8, 9]])

In [182]:
ar2=np.array([[8, 6, 9],
       [3, 8, 4],
       [7, 8, 0]])

In [183]:
ar2

array([[8, 6, 9],
       [3, 8, 4],
       [7, 8, 0]])

In [184]:
ar1+ar2

array([[11,  8, 14],
       [ 3, 13,  6],
       [16, 16,  9]])

In [185]:
[1,2,3]+[4,5,6] 
#list cant perform matrix operations , numpy allows matrix operations

[1, 2, 3, 4, 5, 6]

In [186]:
ar1*ar2

array([[24, 12, 45],
       [ 0, 40,  8],
       [63, 64,  0]])

In [187]:
ar1

array([[3, 2, 5],
       [0, 5, 2],
       [9, 8, 9]])

In [188]:
np.sqrt(ar1)

array([[1.73205081, 1.41421356, 2.23606798],
       [0.        , 2.23606798, 1.41421356],
       [3.        , 2.82842712, 3.        ]])

In [189]:
ar2

array([[8, 6, 9],
       [3, 8, 4],
       [7, 8, 0]])

In [190]:
np.where(ar2>7)

(array([0, 0, 1, 2], dtype=int64), array([0, 2, 1, 1], dtype=int64))

In [191]:
type(np.where(ar2>7))

tuple

In [192]:
np.count_nonzero(ar1)

8

In [193]:
np.nonzero(ar2)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [194]:
ar2[1,1]=0

In [195]:
np.nonzero(ar2)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1], dtype=int64))